<?php

namespace MONSITE\PlateformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    
    public function getLikeQueryBuilder($pattern){
        
        return $this
                ->createQueryBuilder('c')
                ->where('c.name LIKE :pattern')
                ->setParameter('pattern', $pattern);
    }
    
    public function myFindAll(){
        
        $queryBuilder = $this->createQueryBuilder('c');
        
        $query = $queryBuilder->getQuery();
        return $query;
    }
}
